import type { CatalogItem } from "./items";

/**
 * Placeholder catalog shown until real photos are uploaded through /admin.
 * Stock photography (Pexels License — free for commercial use), stored
 * locally under public/gallery-seed/. Used only as a fallback when Blob
 * storage has no items.json yet (e.g. Blob isn't configured, or the
 * catalog is genuinely empty) — real uploads always take priority.
 */
export const SEED_ITEMS: CatalogItem[] = [
  {
    id: "seed-notebooks",
    imageUrl: "/gallery-seed/notebooks-stack.jpg",
    nameEn: "5-Subject Spiral Notebooks",
    nameAr: "دفاتر حلقية 5 مواد",
    descriptionEn: "Sturdy spiral-bound notebooks in a range of colors, for school or office.",
    descriptionAr: "دفاتر حلقية متينة بألوان متعددة، للاستخدام المدرسي والمكتبي.",
    featured: true,
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "seed-pens",
    imageUrl: "/gallery-seed/pens-notes.jpg",
    nameEn: "Assorted Pens & Sticky Notes",
    nameAr: "أقلام متنوعة وأوراق لاصقة",
    descriptionEn: "A colorful mix of pens alongside sticky notes for everyday writing.",
    descriptionAr: "تشكيلة ملونة من الأقلام مع الأوراق اللاصقة للكتابة اليومية.",
    featured: true,
    createdAt: "2026-01-01T00:00:01.000Z",
  },
  {
    id: "seed-binders",
    imageUrl: "/gallery-seed/binders-office.jpg",
    nameEn: "Lever-Arch Files",
    nameAr: "ملفات رافعة (Lever-Arch)",
    descriptionEn: "Durable lever-arch binders for organizing and archiving documents.",
    descriptionAr: "ملفات رافعة متينة لترتيب وأرشفة المستندات في المكتب.",
    featured: true,
    createdAt: "2026-01-01T00:00:02.000Z",
  },
  {
    id: "seed-office",
    imageUrl: "/gallery-seed/notebooks-stapler.jpg",
    nameEn: "Stapler & Notebook Set",
    nameAr: "دباسة مع دفاتر",
    descriptionEn: "A compact stapler alongside notebooks — everyday essentials for any desk.",
    descriptionAr: "دباسة صغيرة مع دفاتر — أساسيات لا يخلو منها أي مكتب.",
    featured: true,
    createdAt: "2026-01-01T00:00:03.000Z",
  },
  {
    id: "seed-pencils",
    imageUrl: "/gallery-seed/colored-pencils.jpg",
    nameEn: "Colored Pencil Set",
    nameAr: "طقم أقلام تلوين",
    descriptionEn: "A full set of colored pencils in a metal case, for school and art projects.",
    descriptionAr: "طقم كامل من أقلام التلوين بعلبة معدنية، للمدرسة ومشاريع الرسم.",
    featured: true,
    createdAt: "2026-01-01T00:00:04.000Z",
  },
  {
    id: "seed-whiteboard",
    imageUrl: "/gallery-seed/whiteboard-room.jpg",
    nameEn: "Flip-Chart Whiteboard",
    nameAr: "سبورة بيضاء قلابة",
    descriptionEn: "A mobile flip-chart whiteboard with markers, for meetings and presentations.",
    descriptionAr: "سبورة بيضاء متحركة مع أقلام، جاهزة للاجتماعات والعروض التقديمية.",
    featured: true,
    createdAt: "2026-01-01T00:00:05.000Z",
  },
  {
    id: "seed-paper",
    imageUrl: "/gallery-seed/paper-stack.jpg",
    nameEn: "Copy Paper Stack",
    nameAr: "رزمة ورق طباعة",
    descriptionEn: "Clean, bright copy paper — the everyday basic for any office or school.",
    descriptionAr: "ورق طباعة أبيض ناصع — الأساس اليومي لأي مكتب أو مدرسة.",
    featured: false,
    createdAt: "2026-01-01T00:00:06.000Z",
  },
  {
    id: "seed-backpack",
    imageUrl: "/gallery-seed/school-backpack.jpg",
    nameEn: "School Backpack",
    nameAr: "حقيبة مدرسية",
    descriptionEn: "A durable school backpack, sized to carry books and supplies comfortably.",
    descriptionAr: "حقيبة مدرسية متينة، بحجم مناسب لحمل الكتب والمستلزمات بارتياح.",
    featured: false,
    createdAt: "2026-01-01T00:00:07.000Z",
  },
  {
    id: "seed-notebook-plain",
    imageUrl: "/gallery-seed/notebook-plain.jpg",
    nameEn: "Hardcover Notebook",
    nameAr: "دفتر بغلاف مقوى",
    descriptionEn: "A clean hardcover notebook for notes, journaling, or daily planning.",
    descriptionAr: "دفتر بغلاف مقوى، مناسب للملاحظات والتدوين اليومي.",
    featured: false,
    createdAt: "2026-01-01T00:00:08.000Z",
  },
  {
    id: "seed-planner",
    imageUrl: "/gallery-seed/planner-notepad.jpg",
    nameEn: "Planner Notepad",
    nameAr: "مفكرة تخطيط",
    descriptionEn: "A compact planner notepad for daily tasks and reminders.",
    descriptionAr: "مفكرة صغيرة لتنظيم المهام والتذكيرات اليومية.",
    featured: false,
    createdAt: "2026-01-01T00:00:09.000Z",
  },
  {
    id: "seed-notepad-set",
    imageUrl: "/gallery-seed/notepad-flatlay.jpg",
    nameEn: "Notepads & Stationery Set",
    nameAr: "طقم مفكرات وقرطاسية",
    descriptionEn: "A tidy set of notepads and small stationery pieces for the desk.",
    descriptionAr: "طقم مرتب من المفكرات وقطع القرطاسية الصغيرة لسطح المكتب.",
    featured: false,
    createdAt: "2026-01-01T00:00:10.000Z",
  },
  {
    id: "seed-highlighters",
    imageUrl: "/gallery-seed/highlighters.jpg",
    nameEn: "Highlighter Markers",
    nameAr: "أقلام تظليل",
    descriptionEn: "Bright highlighter markers in a range of colors for marking and studying.",
    descriptionAr: "أقلام تظليل بألوان زاهية متعددة، للتمييز والمذاكرة.",
    featured: false,
    createdAt: "2026-01-01T00:00:11.000Z",
  },
  {
    id: "seed-ballpoint",
    imageUrl: "/gallery-seed/ballpoint-pens.jpg",
    nameEn: "Ballpoint Pens",
    nameAr: "أقلام حبر جاف",
    descriptionEn: "Everyday ballpoint pens in assorted colors, smooth and reliable.",
    descriptionAr: "أقلام حبر جاف للاستخدام اليومي بألوان متعددة، كتابة سلسة وموثوقة.",
    featured: false,
    createdAt: "2026-01-01T00:00:12.000Z",
  },
  {
    id: "seed-wooden-pencils",
    imageUrl: "/gallery-seed/wooden-pencils.jpg",
    nameEn: "HB Wooden Pencils",
    nameAr: "أقلام رصاص خشبية HB",
    descriptionEn: "Classic wooden HB pencils, sharpened and ready for school or office use.",
    descriptionAr: "أقلام رصاص خشبية كلاسيكية HB، مبراة وجاهزة للاستخدام المدرسي والمكتبي.",
    featured: false,
    createdAt: "2026-01-01T00:00:13.000Z",
  },
  {
    id: "seed-folders",
    imageUrl: "/gallery-seed/document-folders.jpg",
    nameEn: "Document Folders",
    nameAr: "فولدرات مستندات",
    descriptionEn: "Simple document folders for sorting and carrying paperwork.",
    descriptionAr: "فولدرات مستندات بسيطة لترتيب وحمل الأوراق.",
    featured: false,
    createdAt: "2026-01-01T00:00:14.000Z",
  },
  {
    id: "seed-archive-boxes",
    imageUrl: "/gallery-seed/archive-boxes.jpg",
    nameEn: "Archive Boxes",
    nameAr: "صناديق أرشفة",
    descriptionEn: "Sturdy archive boxes for long-term document storage.",
    descriptionAr: "صناديق أرشفة متينة لحفظ المستندات على المدى الطويل.",
    featured: false,
    createdAt: "2026-01-01T00:00:15.000Z",
  },
  {
    id: "seed-scissors",
    imageUrl: "/gallery-seed/scissors.jpg",
    nameEn: "Office Scissors",
    nameAr: "مقص مكتبي",
    descriptionEn: "Sharp, comfortable office scissors for everyday cutting tasks.",
    descriptionAr: "مقص مكتبي حاد ومريح للاستخدام اليومي.",
    featured: false,
    createdAt: "2026-01-01T00:00:16.000Z",
  },
  {
    id: "seed-paperclips",
    imageUrl: "/gallery-seed/paper-clips.jpg",
    nameEn: "Colored Paper Clips",
    nameAr: "مشابك ورق ملونة",
    descriptionEn: "Colorful paper clips for organizing documents at a glance.",
    descriptionAr: "مشابك ورق بألوان متعددة، لترتيب الأوراق بسهولة.",
    featured: false,
    createdAt: "2026-01-01T00:00:17.000Z",
  },
  {
    id: "seed-tape",
    imageUrl: "/gallery-seed/tape-dispenser.jpg",
    nameEn: "Tape Dispenser",
    nameAr: "علبة لاصق (شريط لاصق)",
    descriptionEn: "A desktop tape dispenser, ready to use for packing and everyday tasks.",
    descriptionAr: "علبة شريط لاصق مكتبية، جاهزة للاستخدام اليومي والتغليف.",
    featured: false,
    createdAt: "2026-01-01T00:00:18.000Z",
  },
  {
    id: "seed-watercolor",
    imageUrl: "/gallery-seed/watercolor-paints.jpg",
    nameEn: "Watercolor Paint Set",
    nameAr: "طقم ألوان مائية",
    descriptionEn: "A vibrant watercolor paint set with brushes for art class or hobby painting.",
    descriptionAr: "طقم ألوان مائية زاهية مع فرش، لحصص الفن والرسم.",
    featured: false,
    createdAt: "2026-01-01T00:00:19.000Z",
  },
  {
    id: "seed-geometry",
    imageUrl: "/gallery-seed/geometry-set.jpg",
    nameEn: "Geometry Set",
    nameAr: "طقم هندسة",
    descriptionEn: "A compass, ruler, and pencil set for math class and technical drawing.",
    descriptionAr: "طقم يضم فرجار ومسطرة وقلم رصاص، لحصص الرياضيات والرسم الهندسي.",
    featured: false,
    createdAt: "2026-01-01T00:00:20.000Z",
  },
  {
    id: "seed-crayons",
    imageUrl: "/gallery-seed/crayons.jpg",
    nameEn: "Wax Crayons",
    nameAr: "أقلام شمع تلوين",
    descriptionEn: "A colorful set of wax crayons, sized right for young students.",
    descriptionAr: "طقم ملون من أقلام الشمع، بحجم مناسب للطلاب الصغار.",
    featured: false,
    createdAt: "2026-01-01T00:00:21.000Z",
  },
  {
    id: "seed-noticeboard",
    imageUrl: "/gallery-seed/notice-board.jpg",
    nameEn: "Cork Notice Board",
    nameAr: "لوحة إعلانات فلين",
    descriptionEn: "A cork notice board with push pins, for offices and meeting rooms.",
    descriptionAr: "لوحة إعلانات من الفلين مع دبابيس تثبيت، للمكاتب وقاعات الاجتماعات.",
    featured: false,
    createdAt: "2026-01-01T00:00:22.000Z",
  },
  {
    id: "seed-namebadges",
    imageUrl: "/gallery-seed/name-badges.jpg",
    nameEn: "Name Badges",
    nameAr: "بطاقات أسماء",
    descriptionEn: "Blank name badges, ready to print for events and meetings.",
    descriptionAr: "بطاقات أسماء فارغة، جاهزة للطباعة للفعاليات والاجتماعات.",
    featured: false,
    createdAt: "2026-01-01T00:00:23.000Z",
  },
  {
    id: "seed-desk-organizer",
    imageUrl: "/gallery-seed/desk-organizer.jpg",
    nameEn: "Desk Organizer",
    nameAr: "منظم مكتب",
    descriptionEn: "A compact desk organizer keeping pens, clips, and pins in order.",
    descriptionAr: "منظم مكتب صغير يرتب الأقلام والمشابك والدبابيس في مكانها.",
    featured: false,
    createdAt: "2026-01-01T00:00:24.000Z",
  },
];
